/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 **/

#include <iostream>

int fibonacci(int n)
{
    if (n < 2)
        return n;
    else
        return fibonacci(n-1) + fibonacci(n-2);
}

int main(int argc, const char * argv[])
{
    int sum, current;

    for (int i = 0;; i++) {
        current = fibonacci(i);
        if (current >= 4000000)
            break;
        if (current % 2 == 0)
            sum += current;
    }

    std::cout << sum << std::endl;

    return 0;
}
